package Vistas;

/**
 *
 * @author Nicolás
 */
public class MenuPreparaciones extends javax.swing.JFrame {

    /**
     * Creates new form MenuIngredientes
     */
    public MenuPreparaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn_crearReceta = new javax.swing.JButton();
        jbtn_modReceta = new javax.swing.JButton();
        jbtn_stockPreparaciones = new javax.swing.JButton();
        jbtn_agregarPreparacion = new javax.swing.JButton();
        jbtn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_crearReceta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Crear.png"))); // NOI18N
        jbtn_crearReceta.setText("Crear Receta");
        jbtn_crearReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_crearRecetaActionPerformed(evt);
            }
        });

        jbtn_modReceta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Modificar.png"))); // NOI18N
        jbtn_modReceta.setText("Modificar receta");
        jbtn_modReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_modRecetaActionPerformed(evt);
            }
        });

        jbtn_stockPreparaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Stock_Consulta.png"))); // NOI18N
        jbtn_stockPreparaciones.setText("Consulta Stock Preparaciones");
        jbtn_stockPreparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_stockPreparacionesActionPerformed(evt);
            }
        });

        jbtn_agregarPreparacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Preparación.png"))); // NOI18N
        jbtn_agregarPreparacion.setText("Agregar Preparación");
        jbtn_agregarPreparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarPreparacionActionPerformed(evt);
            }
        });

        jbtn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Volver.png"))); // NOI18N
        jbtn_volver.setText("Volver");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn_modReceta)
                            .addComponent(jbtn_stockPreparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_agregarPreparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_crearReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jbtn_volver)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jbtn_agregarPreparacion)
                .addGap(18, 18, 18)
                .addComponent(jbtn_stockPreparaciones)
                .addGap(18, 18, 18)
                .addComponent(jbtn_crearReceta)
                .addGap(18, 18, 18)
                .addComponent(jbtn_modReceta)
                .addGap(40, 40, 40)
                .addComponent(jbtn_volver)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_crearRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_crearRecetaActionPerformed
        this.hide();
        MenuCrearReceta menuCrearReceta = new MenuCrearReceta();
        menuCrearReceta.show();
    }//GEN-LAST:event_jbtn_crearRecetaActionPerformed

    private void jbtn_modRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_modRecetaActionPerformed
        this.hide();
        MenuAgregarIng menuAgregarIng = new MenuAgregarIng();
        menuAgregarIng.show();
    }//GEN-LAST:event_jbtn_modRecetaActionPerformed

    private void jbtn_stockPreparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_stockPreparacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_stockPreparacionesActionPerformed

    private void jbtn_agregarPreparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarPreparacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_agregarPreparacionActionPerformed

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        this.hide();
        MenuInicial inicial = new MenuInicial();
        inicial.show();
    }//GEN-LAST:event_jbtn_volverActionPerformed

    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPreparaciones().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_agregarPreparacion;
    private javax.swing.JButton jbtn_crearReceta;
    private javax.swing.JButton jbtn_modReceta;
    private javax.swing.JButton jbtn_stockPreparaciones;
    private javax.swing.JButton jbtn_volver;
    // End of variables declaration//GEN-END:variables
}
