package Vistas.Socios;

import Vistas.MenuInicial;

/**
 *
 * @author Nicolás
 */
public class MenuSocios extends javax.swing.JFrame {

    /**
     * Creates new form MenuIngredientes
     */
    public MenuSocios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn_registrarSocio = new javax.swing.JButton();
        jbtn_modDatosSocio = new javax.swing.JButton();
        jbtn_DesvincularSocio = new javax.swing.JButton();
        jbtn_listadoSocios = new javax.swing.JButton();
        jbtn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_registrarSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Crear.png"))); // NOI18N
        jbtn_registrarSocio.setText("Registrar Socio");
        jbtn_registrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_registrarSocioActionPerformed(evt);
            }
        });

        jbtn_modDatosSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Modificar.png"))); // NOI18N
        jbtn_modDatosSocio.setText("Modificar Datos del Socio");
        jbtn_modDatosSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_modDatosSocioActionPerformed(evt);
            }
        });

        jbtn_DesvincularSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Borrar.png"))); // NOI18N
        jbtn_DesvincularSocio.setText("Desvincular Socio");
        jbtn_DesvincularSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_DesvincularSocioActionPerformed(evt);
            }
        });

        jbtn_listadoSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Stock_Consulta.png"))); // NOI18N
        jbtn_listadoSocios.setText("Listado de Socios");
        jbtn_listadoSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listadoSociosActionPerformed(evt);
            }
        });

        jbtn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Volver.png"))); // NOI18N
        jbtn_volver.setText("Volver");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_volver)
                    .addComponent(jbtn_listadoSocios)
                    .addComponent(jbtn_DesvincularSocio)
                    .addComponent(jbtn_modDatosSocio)
                    .addComponent(jbtn_registrarSocio))
                .addContainerGap(730, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jbtn_registrarSocio)
                .addGap(18, 18, 18)
                .addComponent(jbtn_modDatosSocio)
                .addGap(18, 18, 18)
                .addComponent(jbtn_DesvincularSocio)
                .addGap(18, 18, 18)
                .addComponent(jbtn_listadoSocios)
                .addGap(18, 18, 18)
                .addComponent(jbtn_volver)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_registrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_registrarSocioActionPerformed
        this.hide();
        MenuRegistrarSocio regSocio = new MenuRegistrarSocio();
        regSocio.show();
    }//GEN-LAST:event_jbtn_registrarSocioActionPerformed

    private void jbtn_modDatosSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_modDatosSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_modDatosSocioActionPerformed

    private void jbtn_DesvincularSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_DesvincularSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_DesvincularSocioActionPerformed

    private void jbtn_listadoSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listadoSociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_listadoSociosActionPerformed

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        this.hide();
        MenuInicial inicial = new MenuInicial();
        inicial.show();
    }//GEN-LAST:event_jbtn_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSocios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_DesvincularSocio;
    private javax.swing.JButton jbtn_listadoSocios;
    private javax.swing.JButton jbtn_modDatosSocio;
    private javax.swing.JButton jbtn_registrarSocio;
    private javax.swing.JButton jbtn_volver;
    // End of variables declaration//GEN-END:variables
}
