package Vistas;

/**
 *
 * @author Nicolás
 */
public class MenuIngredientes extends javax.swing.JFrame {

    /**
     * Creates new form MenuIngredientes
     */
    public MenuIngredientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn_crearIngrediente = new javax.swing.JButton();
        jbtn_modIngrediente = new javax.swing.JButton();
        jbtn_borrarIngrediente = new javax.swing.JButton();
        jbtn_stockIngredientes = new javax.swing.JButton();
        jbtn_recepcionIngredientes = new javax.swing.JButton();
        jbtn_ajustePerdida = new javax.swing.JButton();
        jbtn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_crearIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Crear.png"))); // NOI18N
        jbtn_crearIngrediente.setText("Crear Ingrediente");
        jbtn_crearIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_crearIngredienteActionPerformed(evt);
            }
        });

        jbtn_modIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Modificar.png"))); // NOI18N
        jbtn_modIngrediente.setText("Modificar ingrediente");
        jbtn_modIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_modIngredienteActionPerformed(evt);
            }
        });

        jbtn_borrarIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Borrar.png"))); // NOI18N
        jbtn_borrarIngrediente.setText("Borrar ingrediente");
        jbtn_borrarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_borrarIngredienteActionPerformed(evt);
            }
        });

        jbtn_stockIngredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Stock_Consulta.png"))); // NOI18N
        jbtn_stockIngredientes.setText("Consulta Stock ingredientes");
        jbtn_stockIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_stockIngredientesActionPerformed(evt);
            }
        });

        jbtn_recepcionIngredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/RecepcionIngredientes.png"))); // NOI18N
        jbtn_recepcionIngredientes.setText("Recepción de ingredientes");
        jbtn_recepcionIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_recepcionIngredientesActionPerformed(evt);
            }
        });

        jbtn_ajustePerdida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Perdida.png"))); // NOI18N
        jbtn_ajustePerdida.setText("Ajuste de pérdida");
        jbtn_ajustePerdida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ajustePerdidaActionPerformed(evt);
            }
        });

        jbtn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Volver.png"))); // NOI18N
        jbtn_volver.setText("Volver");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_volver)
                    .addComponent(jbtn_ajustePerdida)
                    .addComponent(jbtn_recepcionIngredientes)
                    .addComponent(jbtn_stockIngredientes)
                    .addComponent(jbtn_borrarIngrediente)
                    .addComponent(jbtn_modIngrediente)
                    .addComponent(jbtn_crearIngrediente))
                .addContainerGap(718, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jbtn_crearIngrediente)
                .addGap(18, 18, 18)
                .addComponent(jbtn_modIngrediente)
                .addGap(18, 18, 18)
                .addComponent(jbtn_borrarIngrediente)
                .addGap(18, 18, 18)
                .addComponent(jbtn_stockIngredientes)
                .addGap(18, 18, 18)
                .addComponent(jbtn_recepcionIngredientes)
                .addGap(18, 18, 18)
                .addComponent(jbtn_ajustePerdida)
                .addGap(18, 18, 18)
                .addComponent(jbtn_volver)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_crearIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_crearIngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_crearIngredienteActionPerformed

    private void jbtn_modIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_modIngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_modIngredienteActionPerformed

    private void jbtn_borrarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_borrarIngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_borrarIngredienteActionPerformed

    private void jbtn_stockIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_stockIngredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_stockIngredientesActionPerformed

    private void jbtn_recepcionIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_recepcionIngredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_recepcionIngredientesActionPerformed

    private void jbtn_ajustePerdidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ajustePerdidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_ajustePerdidaActionPerformed

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        this.hide();
        MenuInicial inicial = new MenuInicial();
        inicial.show();
    }//GEN-LAST:event_jbtn_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuIngredientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_ajustePerdida;
    private javax.swing.JButton jbtn_borrarIngrediente;
    private javax.swing.JButton jbtn_crearIngrediente;
    private javax.swing.JButton jbtn_modIngrediente;
    private javax.swing.JButton jbtn_recepcionIngredientes;
    private javax.swing.JButton jbtn_stockIngredientes;
    private javax.swing.JButton jbtn_volver;
    // End of variables declaration//GEN-END:variables
}
