package Vistas;

import CakeControl.Ingrediente;
import Controladores.ControladorIngrediente;

/**
 *
 * @author NCR
 */
public class MenuPerdidaIng extends javax.swing.JFrame {

    /**
     * Creates new form MenuRecepcionIng
     */
    public MenuPerdidaIng() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_codigo = new javax.swing.JLabel();
        jtxt_codigo = new javax.swing.JTextField();
        jlbl_nombre = new javax.swing.JLabel();
        jtxt_nombre = new javax.swing.JTextField();
        jlbl_cantPerdida = new javax.swing.JLabel();
        jtxt_cantPerdida = new javax.swing.JTextField();
        jbtn_buscarIng = new javax.swing.JButton();
        jbtn_perdida = new javax.swing.JButton();
        jbtn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbl_codigo.setText("Ingrese código de ingrediente");

        jtxt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_codigoActionPerformed(evt);
            }
        });

        jlbl_nombre.setText("Nombre del producto");

        jtxt_nombre.setEnabled(false);

        jlbl_cantPerdida.setText("Cantidad perdida");

        jbtn_buscarIng.setText("Buscar Ingrediente");
        jbtn_buscarIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarIngActionPerformed(evt);
            }
        });

        jbtn_perdida.setText("Informar Perdidas");
        jbtn_perdida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_perdidaActionPerformed(evt);
            }
        });

        jbtn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Volver.png"))); // NOI18N
        jbtn_volver.setText("Volver");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbl_cantPerdida)
                    .addComponent(jlbl_codigo)
                    .addComponent(jlbl_nombre))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_buscarIng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxt_cantPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_volver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_perdida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_codigo)
                    .addComponent(jtxt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscarIng))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_nombre)
                    .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_cantPerdida)
                    .addComponent(jtxt_cantPerdida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_perdida))
                .addGap(18, 18, 18)
                .addComponent(jbtn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_codigoActionPerformed

    private void jbtn_buscarIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarIngActionPerformed
        //Crea objetos de clases
        ControladorIngrediente contIng = new ControladorIngrediente();
        Ingrediente ing = new Ingrediente();

        //Captura la información del formulario y la lleva al controlador
        ing.setCodigo(Integer.parseInt(this.jtxt_codigo.getText()));
        
        
        //Conexión bd y query
        contIng.buscarIngRecepcion();
        
        //Llena campos
        jtxt_nombre.setText(ing.getNombre());
    }//GEN-LAST:event_jbtn_buscarIngActionPerformed

    private void jbtn_perdidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_perdidaActionPerformed
        //Crea objetos de clases
        ControladorIngrediente contIng = new ControladorIngrediente();
        Ingrediente ingrediente = new Ingrediente();
        
        //Funcion para rescatar stock actualizado de BD
        
        contIng.stockAct();
        
        //Captura la información del formulario y la lleva al controlador
        ingrediente.setCodigo(Integer.parseInt(this.jtxt_codigo.getText()));
        ingrediente.setStock(ingrediente.getStock()-Integer.parseInt(this.jtxt_cantPerdida.getText()));
        
        //Conexión bd y query
        contIng.recepcionarIngrediente();
        
        //Limpia campos
        jtxt_codigo.setText(null);
        jtxt_cantPerdida.setText(null);
        jtxt_nombre.setText(null);
    }//GEN-LAST:event_jbtn_perdidaActionPerformed

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        this.hide();
        MenuIngredientes menuIng = new MenuIngredientes();
        menuIng.show();
    }//GEN-LAST:event_jbtn_volverActionPerformed

    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPerdidaIng().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_buscarIng;
    private javax.swing.JButton jbtn_perdida;
    private javax.swing.JButton jbtn_volver;
    private javax.swing.JLabel jlbl_cantPerdida;
    private javax.swing.JLabel jlbl_codigo;
    private javax.swing.JLabel jlbl_nombre;
    private javax.swing.JTextField jtxt_cantPerdida;
    private javax.swing.JTextField jtxt_codigo;
    private javax.swing.JTextField jtxt_nombre;
    // End of variables declaration//GEN-END:variables
}
