package Vistas.Socios;

import Vistas.MenuInicial;
import javax.swing.JFormattedTextField;

/**
 *
 * @author c4dtu
 */
public class MenuRegistrarSocio extends javax.swing.JFrame {

    /**
     * Creates new form MenuRegistrarSocio
     */
    public MenuRegistrarSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_numrunSocio = new javax.swing.JLabel();
        jlbl_dvrunSocio = new javax.swing.JLabel();
        jlbl_nombreSocio = new javax.swing.JLabel();
        jlbl_direccionSocio = new javax.swing.JLabel();
        jlbl_celularSocio = new javax.swing.JLabel();
        jlbl_correoSocio = new javax.swing.JLabel();
        jlbl_fecnacSocio = new javax.swing.JLabel();
        jtxt_numrun = new javax.swing.JFormattedTextField();
        jtxt_dvrun = new javax.swing.JFormattedTextField();
        jtxt_nombreSocio = new javax.swing.JFormattedTextField();
        jtxt_direccion = new javax.swing.JFormattedTextField();
        jtxt_celular = new javax.swing.JFormattedTextField();
        jtxt_correo = new javax.swing.JFormattedTextField();
        jtxt_fecnac = new javax.swing.JFormattedTextField();
        jbtn_volver = new javax.swing.JButton();
        jbtn_aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbl_numrunSocio.setText("RUT sin dígito verificador");

        jlbl_dvrunSocio.setText("Dígito verificador");

        jlbl_nombreSocio.setText("Nombre completo");

        jlbl_direccionSocio.setText("Dirección");

        jlbl_celularSocio.setText("Número de celular");

        jlbl_correoSocio.setText("Correo electrónico");

        jlbl_fecnacSocio.setText("Fecha de nacimiento");

        jtxt_numrun.setText("123456789");
        jtxt_numrun.setToolTipText("");

        jtxt_dvrun.setText("0");

        jtxt_nombreSocio.setText("Juán Pérez");

        jtxt_direccion.setText("Sargento Aldea 925");

        jtxt_celular.setText("912345678");

        jtxt_correo.setText("contacto@text.com");

        jtxt_fecnac.setText("10/11/1999");

        jbtn_volver.setText("Volver");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });

        jbtn_aceptar.setText("Aceptar");
        jbtn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtn_aceptar)
                    .addComponent(jlbl_fecnacSocio)
                    .addComponent(jlbl_correoSocio)
                    .addComponent(jlbl_celularSocio)
                    .addComponent(jlbl_direccionSocio)
                    .addComponent(jlbl_nombreSocio)
                    .addComponent(jlbl_dvrunSocio)
                    .addComponent(jlbl_numrunSocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt_dvrun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addComponent(jtxt_nombreSocio)
                    .addComponent(jtxt_numrun, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_fecnac, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_volver))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_numrunSocio)
                    .addComponent(jtxt_numrun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_dvrunSocio)
                    .addComponent(jtxt_dvrun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_nombreSocio)
                    .addComponent(jtxt_nombreSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_direccionSocio)
                    .addComponent(jtxt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_celularSocio)
                    .addComponent(jtxt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_correoSocio)
                    .addComponent(jtxt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_fecnacSocio)
                    .addComponent(jtxt_fecnac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_aceptar)
                    .addComponent(jbtn_volver))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        this.hide();
        MenuInicial inicial = new MenuInicial();
        inicial.show();
    }//GEN-LAST:event_jbtn_volverActionPerformed

    private void jbtn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRegistrarSocio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_aceptar;
    private javax.swing.JButton jbtn_volver;
    private javax.swing.JLabel jlbl_celularSocio;
    private javax.swing.JLabel jlbl_correoSocio;
    private javax.swing.JLabel jlbl_direccionSocio;
    private javax.swing.JLabel jlbl_dvrunSocio;
    private javax.swing.JLabel jlbl_fecnacSocio;
    private javax.swing.JLabel jlbl_nombreSocio;
    private javax.swing.JLabel jlbl_numrunSocio;
    private javax.swing.JFormattedTextField jtxt_celular;
    private javax.swing.JFormattedTextField jtxt_correo;
    private javax.swing.JFormattedTextField jtxt_direccion;
    private javax.swing.JFormattedTextField jtxt_dvrun;
    private javax.swing.JFormattedTextField jtxt_fecnac;
    private javax.swing.JFormattedTextField jtxt_nombreSocio;
    private javax.swing.JFormattedTextField jtxt_numrun;
    // End of variables declaration//GEN-END:variables

    public JFormattedTextField getJtxt_celular() {
        return jtxt_celular;
    }

    public void setJtxt_celular(JFormattedTextField jtxt_celular) {
        this.jtxt_celular = jtxt_celular;
    }

    public JFormattedTextField getJtxt_correo() {
        return jtxt_correo;
    }

    public void setJtxt_correo(JFormattedTextField jtxt_correo) {
        this.jtxt_correo = jtxt_correo;
    }

    public JFormattedTextField getJtxt_direccion() {
        return jtxt_direccion;
    }

    public void setJtxt_direccion(JFormattedTextField jtxt_direccion) {
        this.jtxt_direccion = jtxt_direccion;
    }

    public JFormattedTextField getJtxt_dvrun() {
        return jtxt_dvrun;
    }

    public void setJtxt_dvrun(JFormattedTextField jtxt_dvrun) {
        this.jtxt_dvrun = jtxt_dvrun;
    }

    public JFormattedTextField getJtxt_fecnac() {
        return jtxt_fecnac;
    }

    public void setJtxt_fecnac(JFormattedTextField jtxt_fecnac) {
        this.jtxt_fecnac = jtxt_fecnac;
    }

    public JFormattedTextField getJtxt_nombreSocio() {
        return jtxt_nombreSocio;
    }

    public void setJtxt_nombreSocio(JFormattedTextField jtxt_nombreSocio) {
        this.jtxt_nombreSocio = jtxt_nombreSocio;
    }

    public JFormattedTextField getJtxt_numrun() {
        return jtxt_numrun;
    }

    public void setJtxt_numrun(JFormattedTextField jtxt_numrun) {
        this.jtxt_numrun = jtxt_numrun;
    }

}
