package Vistas.Socios;

import CakeControl.Socio;
import Controladores.controladorSocio;
import Vistas.MenuInicial;

/**
 *
 * @author c4dtu
 */
public class MenuRegistrarSocio extends javax.swing.JFrame {

    /**
     * Creates new form MenuRegistrarSocio
     */
    public MenuRegistrarSocio() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_numrunSocio = new javax.swing.JLabel();
        jlbl_dvrunSocio = new javax.swing.JLabel();
        jlbl_nombreSocio = new javax.swing.JLabel();
        jlbl_direccionSocio = new javax.swing.JLabel();
        jlbl_celularSocio = new javax.swing.JLabel();
        jlbl_correoSocio = new javax.swing.JLabel();
        jlbl_fecnacSocio = new javax.swing.JLabel();
        jbtn_volver = new javax.swing.JButton();
        jbtn_aceptar = new javax.swing.JButton();
        jtxt_numrun = new javax.swing.JTextField();
        jtxt_dvrun = new javax.swing.JTextField();
        jtxt_nombreSocio = new javax.swing.JTextField();
        jtxt_direccion = new javax.swing.JTextField();
        jtxt_celular = new javax.swing.JTextField();
        jtxt_correo = new javax.swing.JTextField();
        jtxt_fecnac = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbl_numrunSocio.setText("RUT sin dígito verificador");

        jlbl_dvrunSocio.setText("Dígito verificador");

        jlbl_nombreSocio.setText("Nombre completo");

        jlbl_direccionSocio.setText("Dirección");

        jlbl_celularSocio.setText("Número de celular");

        jlbl_correoSocio.setText("Correo electrónico");

        jlbl_fecnacSocio.setText("Fecha de nacimiento");

        jbtn_volver.setText("Volver");
        jbtn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverActionPerformed(evt);
            }
        });

        jbtn_aceptar.setText("Aceptar");
        jbtn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_aceptarActionPerformed(evt);
            }
        });

        jtxt_numrun.setToolTipText("");
        jtxt_numrun.setActionCommand("<Not Set>");
        jtxt_numrun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_numrunActionPerformed(evt);
            }
        });

        jtxt_nombreSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombreSocioActionPerformed(evt);
            }
        });

        jtxt_fecnac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_fecnacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtn_aceptar)
                    .addComponent(jlbl_fecnacSocio)
                    .addComponent(jlbl_correoSocio)
                    .addComponent(jlbl_celularSocio)
                    .addComponent(jlbl_direccionSocio)
                    .addComponent(jlbl_nombreSocio)
                    .addComponent(jlbl_dvrunSocio)
                    .addComponent(jlbl_numrunSocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn_volver)
                    .addComponent(jtxt_numrun, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_dvrun, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_nombreSocio)
                    .addComponent(jtxt_direccion)
                    .addComponent(jtxt_correo, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(jtxt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_fecnac, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(554, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_numrunSocio)
                    .addComponent(jtxt_numrun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_dvrunSocio)
                    .addComponent(jtxt_dvrun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_nombreSocio)
                    .addComponent(jtxt_nombreSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_direccionSocio)
                    .addComponent(jtxt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_celularSocio)
                    .addComponent(jtxt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_correoSocio)
                    .addComponent(jtxt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_fecnacSocio)
                    .addComponent(jtxt_fecnac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_aceptar)
                    .addComponent(jbtn_volver))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverActionPerformed
        this.hide();
        MenuSocios menuSocios = new MenuSocios();
        menuSocios.show();
    }//GEN-LAST:event_jbtn_volverActionPerformed

    private void jbtn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_aceptarActionPerformed
        controladorSocio contSocio = new controladorSocio();
        Socio socio = new Socio();
        socio.setNumrun(Integer.parseInt(this.jtxt_numrun.getText()));
        socio.setDvrun(this.jtxt_dvrun.getText().charAt(0));
        socio.setNombre(this.jtxt_nombreSocio.getText());
        socio.setDireccion(this.jtxt_direccion.getText());
        socio.setCelular(this.jtxt_celular.getText());
        socio.setCorreo(this.jtxt_correo.getText());
        socio.setCantCompra(0);
        contSocio.ingresarSocio();
    }//GEN-LAST:event_jbtn_aceptarActionPerformed

    private void jtxt_fecnacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_fecnacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_fecnacActionPerformed

    private void jtxt_nombreSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombreSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombreSocioActionPerformed

    private void jtxt_numrunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_numrunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_numrunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRegistrarSocio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_aceptar;
    private javax.swing.JButton jbtn_volver;
    private javax.swing.JLabel jlbl_celularSocio;
    private javax.swing.JLabel jlbl_correoSocio;
    private javax.swing.JLabel jlbl_direccionSocio;
    private javax.swing.JLabel jlbl_dvrunSocio;
    private javax.swing.JLabel jlbl_fecnacSocio;
    private javax.swing.JLabel jlbl_nombreSocio;
    private javax.swing.JLabel jlbl_numrunSocio;
    private javax.swing.JTextField jtxt_celular;
    private javax.swing.JTextField jtxt_correo;
    private javax.swing.JTextField jtxt_direccion;
    private javax.swing.JTextField jtxt_dvrun;
    private javax.swing.JTextField jtxt_fecnac;
    private javax.swing.JTextField jtxt_nombreSocio;
    private javax.swing.JTextField jtxt_numrun;
    // End of variables declaration//GEN-END:variables


}
